version: '3.7'

services:

  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    platform: linux/amd64
    volumes:
      - ./configs/elasticsearch/config.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./docker_volumes/elasticsearch/data:/var/lib/elasticsearch/data
    environment:
      ES_JAVA_OPTS: '-Xmx512m -Xms512m'
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      discovery.type: single-node
    env_file:
      - ./.env
    networks:
      - elk
    ports:
      - ${ELASTIC_PORTS_1}:${ELASTIC_PORTS_1}
      - ${ELASTIC_PORTS_2}:${ELASTIC_PORTS_2}
  
  logstash:
    image: logstash:${ELASTIC_VERSION}
    platform: linux/amd64
    volumes:
      - ./configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines:ro
    environment:
      LS_JAVA_OPTS: '-Xmx512m -Xms512m'
    ports:
      - ${LOGSTASH_PORTS_1}:${LOGSTASH_PORTS_1}
      - ${LOGSTASH_PORTS_2}:${LOGSTASH_PORTS_2}
      - ${LOGSTASH_PORTS_3}:${LOGSTASH_PORTS_3}
    env_file:
      - ./.env
    networks:
      - elk
    depends_on:
      - elasticsearch
  
  kibana:
    image: kibana:${ELASTIC_VERSION}
    platform: linux/amd64
    depends_on:
      - elasticsearch
    volumes:
      - ./configs/kibana/config.yml:/usr/share/kibana/config/kibana.yml:ro
    env_file:
      - ./.env
    networks:
      - elk
    ports:
      - ${KIBANA_PORTS}:${KIBANA_PORTS}

  beats:
    image: elastic/filebeat:${ELASTIC_VERSION}
    volumes:
      - ./configs/filebeat/config.yml:/usr/share/filebeat/filebeat.yml:ro
      - .${PATH_TO_LOGS}:${PATH_TO_LOGS}:ro
    env_file:
      - ./.env
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge