filebeat.inputs:
  - type: log
    enabled: true
    # Проброс логов по пути
    paths:
      - ${PATH_TO_LOGS}${NAME_LOGS}
    # В fields мы можем указать дополнительные поля, 
    # а затем в logstash вытаскивать их 
    # и делать какую-нибудь дополнительную работу с логами
    fields:
      # Название нашего сервиса
      service: host_metrics_app

output.logstash:
  # При запуске вне докера указать адрес хоста logstash 
  hosts: ['${LOGSTASH_HOST}']